services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend

  contracts:
    build:
      context: apps/local-node
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    networks:
      - backend
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8545",
          "-X",
          "POST",
          "-H",
          "Content-Type: application/json",
          "-d",
          '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}',
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  indexer-db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid
    networks:
      - backend

  indexer:
    build:
      context: .
      dockerfile: apps/indexer/Dockerfile.indexer
      args:
        - CONFIG_FILE=config/ens.local.config.ts
        - SCHEMA=public
    environment:
      - DATABASE_URL=postgres://postgres:admin@indexer-db:5432/postgres
      - DAO_ID=ENS
      - NETWORK=anvil
      - RPC_URL=http://contracts:8545
      - CHAIN_ID=31337
      - MAX_REQUESTS_PER_SECOND=10
      - POLLING_INTERVAL=1000
      - PORT=42069

    depends_on:
      indexer-db:
        condition: service_started
      contracts:
        condition: service_healthy
    ports:
      - "42069:42069"
    networks:
      - backend

  gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - indexer
    networks:
      - backend

networks:
  backend:
    driver: bridge
