services:
  db:
    image: postgres:16.2
    container_name: gateway-postgres-db
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres

  redis:
    image: redis:latest
    container_name: gateway-redis
    ports:
      - '6379:6379'
    restart: always
