services:
  db:
    image: postgres:16.2
    container_name: anticapture-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    tmpfs:
      - /var/lib/postgresql/data # in memory volume

  redis:
    image: redis:latest
    container_name: gateway-redis
    ports:
      - "6379:6379"
    restart: always

  contracts:
    build:
      context: apps/indexer/contracts
      dockerfile: Dockerfile
    container_name: anticapture-contracts
    ports:
      - "8545:8545"

  indexer:
    build:
      context: apps/indexer
    container_name: anticapture-indexer
    environment:
      - DATABASE_URL=postgres://postgres:admin@anticapture-db:5432/postgres
      - DAO_ID=ENS
      - NETWORK=anvil
      - RPC_URL=http://anticapture-contracts:8545
    depends_on:
      - db
      - contracts
    ports:
      - "42069:42069"
