services:

  contracts:
    build:
      context: apps/local-node
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/anvil-ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  indexer-db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    networks:
      - backend

  indexer:
    build:
      context: .
      dockerfile: apps/indexer/Dockerfile.indexer
      args:
        - CONFIG_FILE=config/ens.local.config.ts
        - SCHEMA=public
    environment:
      - DATABASE_URL=postgres://postgres:admin@indexer-db:5432/postgres
      - DAO_ID=ENS
      - NETWORK=anvil
      - RPC_URL=http://contracts:8545
      - CHAIN_ID=31337
      - PORT=42069

    depends_on:
      indexer-db:
        condition: service_started
      contracts:
        condition: service_healthy
    ports:
      - "42069:42069"
    networks:
      - backend

  gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - indexer
    networks:
      - backend

networks:
  backend:
