version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend

  contracts:
    build:
      context: apps/indexer/contracts
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    networks:
      - backend

  indexer-db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    networks:
      - backend

  indexer:
    build:
      context: apps/indexer
    environment:
      - DATABASE_URL=postgres://postgres:admin@indexer-db:5432/postgres
      - DAO_ID=ENS
      - NETWORK=ethereum
      - RPC_URL=http://contracts:8545
    depends_on:
      - indexer-db
      - contracts
    ports:
      - "42069:42069"
    networks:
      - backend

networks:
  backend:
    driver: bridge
