[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.indexer"
buildCommand = "docker build -f ./Dockerfile.indexer ."

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
